
export const getUsers = (req, res, next ) => {
    try {
        res.send("Mike")
    } catch (error) {
        
    }
}